# Secrets Module - Manages secrets across different providers
# Supports: Kubernetes, AWS Secrets Manager, Azure Key Vault, Local .env

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.24"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# ==============================================================================
# LOCAL DEVELOPMENT (Docker Compose)
# ==============================================================================

resource "local_file" "env_file" {
  count    = var.environment == "local" ? 1 : 0
  filename = var.env_file_path

  content = <<-EOT
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Generated: ${timestamp()}
# Environment: ${var.environment}

# Database
MONGODB_URI=${var.mongodb_uri}
QDRANT_URL=${var.qdrant_url}
REDIS_URL=${var.redis_url}

# Message Queue
KAFKA_BROKERS=${var.kafka_brokers}
KAFKA_CLIENT_ID=next-level-real-estate

# AI Services
ANTHROPIC_API_KEY=${var.anthropic_api_key}
OPENAI_API_KEY=${var.openai_api_key}
ELEVENLABS_API_KEY=${var.elevenlabs_api_key}

# Communication - Twilio
TWILIO_ACCOUNT_SID=${var.twilio_account_sid}
TWILIO_AUTH_TOKEN=${var.twilio_auth_token}
TWILIO_PHONE_NUMBER=${var.twilio_phone_number}

# Email - ProtonMail
PROTONMAIL_EMAIL=${var.protonmail_email}
PROTONMAIL_APP_PASSWORD=${var.protonmail_app_password}
FROM_NAME=${var.from_name}
FROM_EMAIL=${var.from_email}

# Lead Sources
GOOGLE_ADS_CLIENT_ID=${var.google_ads_client_id}
GOOGLE_ADS_CLIENT_SECRET=${var.google_ads_client_secret}
GOOGLE_ADS_DEVELOPER_TOKEN=${var.google_ads_developer_token}
GOOGLE_ADS_REFRESH_TOKEN=${var.google_ads_refresh_token}
GOOGLE_ADS_CUSTOMER_ID=${var.google_ads_customer_id}

ZILLOW_API_KEY=${var.zillow_api_key}
ZILLOW_WEBHOOK_SECRET=${var.zillow_webhook_secret}

REALGEEKS_API_USERNAME=${var.realgeeks_api_username}
REALGEEKS_API_PASSWORD=${var.realgeeks_api_password}

# Services
API_GATEWAY_PORT=3000
LEAD_SERVICE_PORT=3001
CALLING_SERVICE_PORT=3002
EMAIL_SERVICE_PORT=3003

# Security
JWT_SECRET=${var.jwt_secret}
API_KEY_SALT=${var.api_key_salt}

# Observability
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317

# Environment
NODE_ENV=${var.node_env}
LOG_LEVEL=${var.log_level}
EOT

  file_permission = "0600"  # Owner read/write only
}

# ==============================================================================
# KUBERNETES SECRETS
# ==============================================================================

resource "kubernetes_namespace" "nlre" {
  count = var.create_kubernetes_resources ? 1 : 0

  metadata {
    name = var.kubernetes_namespace

    labels = {
      environment = var.environment
      managed-by  = "terraform"
    }
  }
}

resource "kubernetes_secret" "nlre_secrets" {
  count = var.create_kubernetes_resources ? 1 : 0

  metadata {
    name      = "nlre-secrets"
    namespace = var.kubernetes_namespace

    labels = {
      app         = "next-level-real-estate"
      environment = var.environment
      managed-by  = "terraform"
    }
  }

  data = {
    # AI Services
    ANTHROPIC_API_KEY    = var.anthropic_api_key
    OPENAI_API_KEY       = var.openai_api_key
    ELEVENLABS_API_KEY   = var.elevenlabs_api_key

    # Communication
    TWILIO_ACCOUNT_SID   = var.twilio_account_sid
    TWILIO_AUTH_TOKEN    = var.twilio_auth_token
    TWILIO_PHONE_NUMBER  = var.twilio_phone_number

    # Email
    PROTONMAIL_EMAIL            = var.protonmail_email
    PROTONMAIL_APP_PASSWORD     = var.protonmail_app_password
    FROM_NAME                   = var.from_name
    FROM_EMAIL                  = var.from_email

    # Lead Sources
    GOOGLE_ADS_CLIENT_ID        = var.google_ads_client_id
    GOOGLE_ADS_CLIENT_SECRET    = var.google_ads_client_secret
    GOOGLE_ADS_DEVELOPER_TOKEN  = var.google_ads_developer_token
    GOOGLE_ADS_REFRESH_TOKEN    = var.google_ads_refresh_token
    GOOGLE_ADS_CUSTOMER_ID      = var.google_ads_customer_id

    ZILLOW_API_KEY              = var.zillow_api_key
    ZILLOW_WEBHOOK_SECRET       = var.zillow_webhook_secret

    REALGEEKS_API_USERNAME      = var.realgeeks_api_username
    REALGEEKS_API_PASSWORD      = var.realgeeks_api_password

    # Security
    JWT_SECRET                  = var.jwt_secret
    API_KEY_SALT                = var.api_key_salt
  }

  type = "Opaque"

  depends_on = [kubernetes_namespace.nlre]
}

# ConfigMap for non-sensitive configuration
resource "kubernetes_config_map" "nlre_config" {
  count = var.create_kubernetes_resources ? 1 : 0

  metadata {
    name      = "nlre-config"
    namespace = var.kubernetes_namespace

    labels = {
      app         = "next-level-real-estate"
      environment = var.environment
      managed-by  = "terraform"
    }
  }

  data = {
    # Database URLs (internal Kubernetes DNS)
    MONGODB_URI     = var.mongodb_uri
    QDRANT_URL      = var.qdrant_url
    REDIS_URL       = var.redis_url
    KAFKA_BROKERS   = var.kafka_brokers

    # Service Ports
    API_GATEWAY_PORT    = "3000"
    LEAD_SERVICE_PORT   = "3001"
    CALLING_SERVICE_PORT = "3002"
    EMAIL_SERVICE_PORT  = "3003"

    # Service URLs (internal)
    LEAD_SERVICE_URL     = "http://lead-service:3001"
    CALLING_SERVICE_URL  = "http://calling-service:3002"
    EMAIL_SERVICE_URL    = "http://email-service:3003"

    # Observability
    OTEL_EXPORTER_OTLP_ENDPOINT = var.otel_endpoint

    # Environment
    NODE_ENV  = var.node_env
    LOG_LEVEL = var.log_level
  }

  depends_on = [kubernetes_namespace.nlre]
}

# ==============================================================================
# AWS SECRETS MANAGER (Production)
# ==============================================================================

resource "aws_secretsmanager_secret" "nlre_secrets" {
  count = var.use_aws_secrets_manager ? 1 : 0

  name_prefix = "nlre-${var.environment}-"
  description = "Next Level Real Estate secrets for ${var.environment}"

  recovery_window_in_days = var.environment == "production" ? 30 : 0

  tags = {
    Environment = var.environment
    ManagedBy   = "terraform"
    Application = "next-level-real-estate"
  }
}

resource "aws_secretsmanager_secret_version" "nlre_secrets" {
  count = var.use_aws_secrets_manager ? 1 : 0

  secret_id = aws_secretsmanager_secret.nlre_secrets[0].id

  secret_string = jsonencode({
    # AI Services
    anthropic_api_key    = var.anthropic_api_key
    openai_api_key       = var.openai_api_key
    elevenlabs_api_key   = var.elevenlabs_api_key

    # Communication
    twilio_account_sid   = var.twilio_account_sid
    twilio_auth_token    = var.twilio_auth_token
    twilio_phone_number  = var.twilio_phone_number

    # Email
    protonmail_email            = var.protonmail_email
    protonmail_app_password     = var.protonmail_app_password
    from_name                   = var.from_name
    from_email                  = var.from_email

    # Lead Sources
    google_ads_client_id        = var.google_ads_client_id
    google_ads_client_secret    = var.google_ads_client_secret
    google_ads_developer_token  = var.google_ads_developer_token
    google_ads_refresh_token    = var.google_ads_refresh_token
    google_ads_customer_id      = var.google_ads_customer_id

    zillow_api_key              = var.zillow_api_key
    zillow_webhook_secret       = var.zillow_webhook_secret

    realgeeks_api_username      = var.realgeeks_api_username
    realgeeks_api_password      = var.realgeeks_api_password

    # Security
    jwt_secret                  = var.jwt_secret
    api_key_salt                = var.api_key_salt
  })
}

# Rotation configuration for production
resource "aws_secretsmanager_secret_rotation" "nlre_secrets" {
  count = var.use_aws_secrets_manager && var.enable_secret_rotation ? 1 : 0

  secret_id           = aws_secretsmanager_secret.nlre_secrets[0].id
  rotation_lambda_arn = var.rotation_lambda_arn

  rotation_rules {
    automatically_after_days = 90
  }
}

# ==============================================================================
# AZURE KEY VAULT (Alternative to AWS)
# ==============================================================================

resource "azurerm_key_vault" "nlre" {
  count = var.use_azure_key_vault ? 1 : 0

  name                = "nlre-${var.environment}-kv"
  location            = var.azure_location
  resource_group_name = var.azure_resource_group
  tenant_id           = var.azure_tenant_id
  sku_name            = "standard"

  enable_rbac_authorization = true
  purge_protection_enabled  = var.environment == "production"

  tags = {
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

# Individual secrets in Azure Key Vault
resource "azurerm_key_vault_secret" "anthropic_key" {
  count = var.use_azure_key_vault ? 1 : 0

  name         = "anthropic-api-key"
  value        = var.anthropic_api_key
  key_vault_id = azurerm_key_vault.nlre[0].id
}

resource "azurerm_key_vault_secret" "openai_key" {
  count = var.use_azure_key_vault ? 1 : 0

  name         = "openai-api-key"
  value        = var.openai_api_key
  key_vault_id = azurerm_key_vault.nlre[0].id
}

# ... Additional secrets (similar pattern)

# ==============================================================================
# GENERATE SECRETS (if not provided)
# ==============================================================================

resource "random_password" "jwt_secret" {
  count = var.jwt_secret == "" ? 1 : 0

  length  = 64
  special = true
}

resource "random_password" "api_key_salt" {
  count = var.api_key_salt == "" ? 1 : 0

  length  = 32
  special = true
}

# ==============================================================================
# EXTERNAL SECRETS OPERATOR (for Kubernetes + Cloud Sync)
# ==============================================================================

# If using External Secrets Operator to sync from AWS/Azure to Kubernetes
resource "kubernetes_manifest" "external_secret" {
  count = var.use_external_secrets_operator ? 1 : 0

  manifest = {
    apiVersion = "external-secrets.io/v1beta1"
    kind       = "ExternalSecret"
    metadata = {
      name      = "nlre-secrets"
      namespace = var.kubernetes_namespace
    }
    spec = {
      refreshInterval = "1h"
      secretStoreRef = {
        name = "aws-secretsmanager"  # or "azure-keyvault"
        kind = "SecretStore"
      }
      target = {
        name           = "nlre-secrets"
        creationPolicy = "Owner"
      }
      dataFrom = [{
        extract = {
          key = aws_secretsmanager_secret.nlre_secrets[0].name
        }
      }]
    }
  }

  depends_on = [aws_secretsmanager_secret_version.nlre_secrets]
}
